### ISSUE TITLE
DateInterval::__construct(): Unknown or bad format (P/([0-9]+) days/D)

### ISSUE THREAD

**Issue by Lach1222** [rafaelpatro/google-customer-reviews#1]
Hi when any order checkout i receive the following error

DateInterval::__construct(): Unknown or bad format (P/([0-9]+) days/D)

Thanks 
L

**Comment by rafaelpatro** [comment]
Hi @Lach1222 

Are you setting Delivery Time? It must be an integer.
![image](https://cloud.githubusercontent.com/assets/13813964/24651766/64a260aa-1905-11e7-84b8-b7a20d2503b7.png)

If you have a time described in Shipping Description like below...
![image](https://cloud.githubusercontent.com/assets/13813964/24652076/b0700130-1906-11e7-8ece-cdac2c905a17.png)

...so you can set a pattern. Something like this:
![image](https://cloud.githubusercontent.com/assets/13813964/24652038/7f78880e-1906-11e7-97a5-f7765eb338cd.png)

Let me know if it works

**Comment by Lach1222** [comment]
Thanks Rafael

That worked
On 4 Apr 2017, at 8:19 pm, Rafael Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Lach1222<https://github.com/Lach1222>

Are you setting Delivery Time? It must be an integer.
[image]<https://cloud.githubusercontent.com/assets/13813964/24651766/64a260aa-1905-11e7-84b8-b7a20d2503b7.png>

If you have a time described in Shipping Description like below...
[image]<https://cloud.githubusercontent.com/assets/13813964/24652076/b0700130-1906-11e7-8ece-cdac2c905a17.png>

...so you can set a pattern. Something like this:
[image]<https://cloud.githubusercontent.com/assets/13813964/24652038/7f78880e-1906-11e7-97a5-f7765eb338cd.png>

Let me know if it works
