### ISSUE TITLE
delivery_country requires customers code

### ISSUE THREAD

**Issue by wssweb** [rafaelpatro/google-customer-reviews#2]
As per: https://support.google.com/merchants/answer/7106244?hl=en#integration

The delivery_country variable requires the customers country on the order be entered, which could be different from the pre-defined value from the backend configuration. 

replacing (line 44 of app\code\community\Quack\GoogleReviews\Block\Gr.php):
`Mage::helper('googlereviews')->getDeliveryCountryCode(),`

with:
`$order->getShippingAddress()->getCountryId(),`

would be better?

**Comment by rafaelpatro** [comment]
Thanks! Can you fix this?
Send a PR so I can merge in project.

**Comment by wssweb** [comment]
Sorry, I do not have git installed, I just downloaded the zip file. 

It just occurred to me as well that if a store had virtual items, and a customer ordered only them the cart would not ask for a shipping address. Which would result in a null value, so you would have to fall back on the billing address

`$order->getBillingAddress()->getCountryId()`

A check would need to be added to cover all the bases. I can not think of a situation where the billing country would not be provided on an order.
