### ISSUE TITLE
Dúvida Prazo

### ISSUE THREAD

**Issue by henriquemnr** [rafaelpatro/google-customer-reviews#6]
Rafael tudo bom?

Estou com problema em configurar a parte do prazo.

No meu caso o prazo é gravado dessa maneira: Sedex - Em média 2 dia(s) úteis. R$7,31

Qual seria a maneira correta para configurar o campo: Estimated Delivery Time (Pattern)

Não pude entender corretamente na documentação.

**Comment by rafaelpatro** [comment]
No seu caso fica assim:
/([0-9]+) dia/

Em 19/06/2017 22:11, "henriquemnr" <notifications@github.com> escreveu:

**Comment by henriquemnr** [comment]
Rafael, show de bola! Funcionou com perfeição!
