### ISSUE TITLE
Localização do review na página.

### ISSUE THREAD

**Issue by smarley2** [rafaelpatro/google-customer-reviews#9]
Olá Rafael,

A localização do review na página fica em qual local?
Ela é configurável?

Obrigado.

**Comment by rafaelpatro** [comment]
Bom dia

* A janela de solicitação de review é exibida na página de sucesso de compra do Magento. A forma de exibição é por conta do Google, e é customizada para diferentes tipos de dispositivos.
* O review é realizado por e-mail, por conta do Google.

No momento este módulo não exibe as avaliações. Você pode ver o resultado das avaliações pelo link a seguir.

    https://www.google.com/shopping/ratings/account/metrics?q=seudominio.com&c=GLOBAL&v=1

Você tb pode exibir o símbolo do Google Avaliações no canto do site, como ilustrado abaixo.
![image](https://user-images.githubusercontent.com/13813964/36098056-a1f0fee0-0fe4-11e8-98de-fd00c8f13e04.png)
Basta adicionar o script a seguir em qualquer página html do seu site, ou adicionar um Widget para exibir o símbolo em várias páginas.
```html
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<script>
  window.renderBadge = function() {
    var ratingBadgeContainer = document.createElement("div");
    document.body.appendChild(ratingBadgeContainer);
    window.gapi.load('ratingbadge', function() {
      window.gapi.ratingbadge.render(ratingBadgeContainer, {"merchant_id": 1234567});
    });
  }
</script>

**Comment by smarley2** [comment]
Ok obrigado, vou testar o modulo e verifica como acrescento o review na
pagina do produto.

Em 12 de fev de 2018 11:12, "Rafael Patro" <notifications@github.com>
escreveu:

**Comment by rafaelpatro** [comment]
Pois é, exibir o review na página do produto seria ótimo. Infelizmente o módulo ainda não faz isso.
Se quiser contribuir com esse recurso, uma PR será muito bem vinda.
Boa sorte!
